from . import crm_lead
from . import crm_team
from . import hr_employee
from . import res_partner
from . import region
from . import service
from . import package
from . import package_level
from . import order_line
from . import order_assignment
from . import technical_task
from . import contract
from . import sign
from . import invoice
from . import invoice_line
from . import payment
from . import vat
from . import wht
from . import sla_violation
from . import tsc_dashboard
