from . import crm_lead
from . import crm_team
from . import hr_employee
from . import res_partner
from . import region
from . import order_line
from . import order_assignment
from . import technical_task
from . import tsc_dashboard
