{
    'name': 'TSC CRM Core',
    'version': '18.0.1.0.0',
    'category': 'CRM',
    'summary': 'TSC/Unitel CRM core module',
    'description': 'Core CRM module extending Odoo 18 for TSC telecom.',
    'author': 'TSC',
    'website': 'https://tsc.la',
    'license': 'LGPL-3',
    'depends': [
        'crm',
        'hr',
        'mail',
        'contacts',
    ],
    'data': [
        'security/tsc_security.xml',
        'security/ir.model.access.csv',
        'data/crm_stage_data.xml',
        'data/notification_templates.xml',
        'views/region_views.xml',
        'views/service_views.xml',
        'views/package_views.xml',
        'views/order_line_views.xml',
        'views/order_assignment_views.xml',
        'views/technical_task_views.xml',
        'views/crm_lead_views.xml',
        'views/crm_team_views.xml',
        'views/hr_employee_views.xml',
        'views/contract_views.xml',
        'views/sign_views.xml',
        'views/invoice_views.xml',
        'views/payment_views.xml',
        'views/vat_views.xml',
        'views/wht_views.xml',
        'views/sla_violation_views.xml',
        'views/tsc_dashboard_views.xml',
        'views/tsc_menu.xml',
    ],
    'installable': True,
    'application': True,
}
