from . import test_region
from . import test_service
from . import test_package
from . import test_package_level
from . import test_order_line
from . import test_crm_lead
from . import test_crm_team
from . import test_hr_employee
from . import test_res_partner
from . import test_order_assignment
from . import test_technical_task
from . import test_contract
from . import test_sign
from . import test_invoice
from . import test_payment
from . import test_vat
from . import test_wht
from . import test_sla_config
from . import test_sla_violation
